name: CI

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run flake8
        run: |
          . venv/bin/activate
          flake8 .

      - name: Run black (check mode)
        run: |
          . venv/bin/activate
          black --check --diff .

      - name: Run isort (check mode)
        run: |
          . venv/bin/activate
          isort --check-only --profile black --diff .

      - name: Run mypy
        run: |
          . venv/bin/activate
          mypy .
